[package]
name = "Battle_Cats_Complete"
version = "0.4.2"
edition = "2024"

[features]
default = []
dev = ["dep:aes", "dep:cbc", "dep:ecb", "dep:block-padding", "dep:md5", "dep:hex"]

[dependencies]
# default
eframe = { version = "0.29", features = ["persistence"] }
image = { version = "0.25", features = ["png", "ico"] }
rfd = "0.15"
zip = "0.6"
regex = "1"
rayon = "1.10"
serde = { version = "1", features = ["derive"] }

# dev
aes = { version = "0.8", optional = true }
cbc = { version = "0.1", optional = true }
ecb = { version = "0.1", optional = true }
block-padding = { version = "0.3", optional = true }
md5 = { version = "0.7", optional = true }
hex = { version = "0.4", optional = true }

[profile.release]
strip = true
opt-level = 3
lto = "thin"
panic = "abort"