[package]
name = "Battle_Cats_Complete"
version = "0.1.0"
edition = "2024"

[dependencies]
# Core encryption standard
aes = "0.8"
# Modes we identified (CBC and ECB)
cbc = "0.1"
ecb = "0.1"
# Handling padding removal
block-padding = "0.3"
# Key hashing ("pack", "battlecats")
md5 = "0.7"
# Reading hex strings
hex = "0.4"
# GUI framework
eframe = { version = "0.29", features = ["persistence"] }
# Handles icon/images
image = { version = "0.25", features = ["png", "ico"] }
# Handles file dialogs
rfd = "0.15"
# Handles file archives
zip = "0.6"
# Handles sorting
regex = "1"
# Handles multi-threading
rayon = "1.10"
# Handles persistance
serde = { version = "1", features = ["derive"] }