name: Auto Build & Release

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Cargo.toml'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  BIN_NAME: "Battle Cats Complete"

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get version
        id: get_version
        run: |
          $VERSION = Select-String -Path Cargo.toml -Pattern '^version' | Select-Object -First 1
          $VERSION = $VERSION.Line.Split('"')[1]
          echo "version=$VERSION" >> $env:GITHUB_OUTPUT
      - name: Cache Cargo Dependencies
        uses: swatinem/rust-cache@v2
        with:
           key: windows-release
      - name: Build Release
        run: cargo build --release --verbose
      - name: Rename and Zip
        run: |
          move target/release/*.exe "${{ env.BIN_NAME }}.exe"
          Compress-Archive -Path "${{ env.BIN_NAME }}.exe" -DestinationPath bcc_windows.zip
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-asset
          path: bcc_windows.zip
          if-no-files-found: error

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Cargo Dependencies
        uses: swatinem/rust-cache@v2
        with:
           key: linux-release
      - name: Build Release
        run: cargo build --release --verbose
      - name: Prepare and Zip
        run: |
          ORIGINAL_BIN_NAME=$(sed -n 's/^name = "\(.*\)"/\1/p' Cargo.toml | head -1)
          mv "target/release/$ORIGINAL_BIN_NAME" "${{ env.BIN_NAME }}"
          chmod +x "${{ env.BIN_NAME }}"
          zip bcc_linux.zip "${{ env.BIN_NAME }}"
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-asset
          path: bcc_linux.zip
          if-no-files-found: error

  create-release:
    name: Draft Release
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get version
        id: get_version
        run: |
          VERSION=$(grep "^version" Cargo.toml | head -1 | awk -F '"' '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: *-asset
          merge-multiple: true
      - name: Create Release & Upload Files
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.MY_RELEASE_TOKEN }}
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Battle Cats Complete v${{ steps.get_version.outputs.version }}
          draft: true
          prerelease: true
          generate_release_notes: true
          files: |
            bcc_windows.zip
            bcc_linux.zip
